# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pure < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/am3o/pure"
  version "1.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/download/v1.0.1/pure_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "10c9043a20e9feceedf347a343378ec7a784ff4195601bbc792b19202ee298b9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Am3o/pure/releases/download/v1.0.1/pure_1.0.1_Darwin_arm64.tar.gz"
    sha256 "f7af40c303af2a32cdaaf178d5daadc8305277425d02400db02827fa0c0acc8e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/download/v1.0.1/pure_1.0.1_Linux_x86_64.tar.gz"
    sha256 "882940ec0a70dfa242bd473d1e67944b96badda8f06e7935002cd7063fce309e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Am3o/pure/releases/download/v1.0.1/pure_1.0.1_Linux_arm64.tar.gz"
    sha256 "49f25a59dcfcbdef5fdae7a131947c342dcebc4fdc74613c1bb9c3de13b3dd20"
  end

  def install
    bin.install "pure"
  end
end
