# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Pure < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "8a9dca150b04c963d6dc110ab33dedb79d228ce38c44f48c924b238b285d5841"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "15f0340e4ebdc65824ea37054e26d99e3f50f876ef1dc33cbbb8450cc49ff20b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "79603cbb54fcf263a1fc64fccacead0bf394a2563e797c8e46aa1be6699b7441"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "d3ef600fbd8e45415c9aa398fc87b39a628ba045f36a11137cc6bd7f25ee4a7e"
  end

  def install
    bin.install "pure"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
