# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Pure < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "d526f9c45bdc2dc8304474a7c7c57f63e97b9b5466be5c0a1e867234ecbdc926"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "446dec09e636dcbcceeb0712f80ac3c06231bd020824eb2bbe0acc8b87571df0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "5e77e4541d495294258b6be781ee2f0067486687cf1a4aef7b80e4e9bae15ce6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Am3o/pure/releases/v1.0.1/pure_1.0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "caef546764b865eebfd1d5d71393c1f8ae4d8be98ff53011d7a6ad9edabaf355"
  end

  def install
    bin.install "pure"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
